verbose: true
startDelay: 6
deathKeepInventory: true
deathKeepLevel: true
damageFromOtherPlayers: false
lang: "ru"
maxCallDistance: 10
maxDistance: 75
preventUsingCommands: true
preventTeleport: true
