verbose: true
startDelay: 10
deathKeepInventory: true
deathKeepLevel: true
damageFromOtherPlayers: false
lang: "en"
maxCallDistance: 10
maxDistance: 35
preventUsingCommands: true
preventTeleport: true