name: Dualist
version: ${project.version}
main: verrok.dualist.Dualist
website: https://github.com/Verrochek/Dualist
authors: [Verrok]
softdepend: [Vault]
api-version: "1.12"
description: Plugin that provides duels
commands:
  duel:
    description: starts duel
    permission: dualist.help